try{
  let a=0
  console.log(b)
  console.log("Program success")
}
catch(error){
  console.log("This is an error")
  console.log(p)
}
finally{
  console.log("I am a good boy")
}